# Generated by Django 3.0.2 on 2020-01-06 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('booked_on_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', help_text='Current status of the booking', max_length=20)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(help_text='Feature Name/Description', max_length=300)),
                ('active', models.BooleanField(help_text='Active/Inactive')),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(help_text='Give a name to the plan', max_length=200, unique=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(help_text='Make a plan active or inactive')),
                ('price', models.FloatField()),
                ('guest_capacity', models.IntegerField(default=1)),
                ('features', models.ManyToManyField(to='domigo.PlanFeature')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booking_entry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='domigo.Booking')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domigo.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='BookingNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='domigo.Booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='domigo.Plan'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booked_by', 'check_in_date', 'check_out_date', 'plan', 'status')},
        ),
    ]
