# Generated by Django 3.0.4 on 2020-03-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='bookingnote',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingregister',
            name='booking_entry',
        ),
        migrations.RemoveField(
            model_name='bookingregister',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='guest_capacity',
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingNote',
        ),
        migrations.DeleteModel(
            name='BookingRegister',
        ),
        migrations.DeleteModel(
            name='PlanFeature',
        ),
    ]
