# Generated by Django 3.0.4 on 2020-03-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0003_planfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(related_name='features', to='domigo.PlanFeature'),
        ),
    ]
