# Generated by Django 3.0.4 on 2020-03-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0004_plan_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Feature Name/Description', max_length=300)),
                ('active', models.BooleanField(help_text='Active/Inactive')),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
