# Generated by Django 3.0.4 on 2020-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0005_petcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeature',
            name='description',
            field=models.CharField(blank=True, help_text='Feature Name/Description', max_length=500, null=True),
        ),
    ]
