# Generated by Django 3.0.4 on 2020-03-29 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0006_planfeature_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Feature Name/Description', max_length=300)),
                ('active', models.BooleanField(help_text='Active/Inactive')),
                ('created_date', models.DateField(auto_now=True)),
                ('pet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domigo.PetCategory')),
                ('price_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domigo.Plan')),
            ],
            options={
                'unique_together': {('pet_category', 'name')},
            },
        ),
    ]
