# Generated by Django 3.0.4 on 2020-03-30 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domigo', '0007_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Feature Name/Description', max_length=300)),
                ('date_of_birth', models.DateField()),
                ('description', models.CharField(help_text='Feature Name/Description', max_length=300)),
                ('Breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domigo.Breed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
