# Generated by Django 3.0.4 on 2020-03-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0008_userpets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpets',
            name='description',
            field=models.CharField(help_text='Write something about your pet or handling instructions.', max_length=300),
        ),
        migrations.AlterField(
            model_name='userpets',
            name='name',
            field=models.CharField(help_text='Name', max_length=300),
        ),
    ]
