# Generated by Django 3.0.4 on 2020-03-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0009_auto_20200330_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=300)),
                ('active', models.BooleanField(help_text='Active/Inactive')),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
