# Generated by Django 3.0.4 on 2020-03-31 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domigo', '0010_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpets',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('booked_on_date', models.DateField(auto_now=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domigo.PaymentMethod')),
                ('userpet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domigo.UserPets')),
            ],
            options={
                'unique_together': {('booked_by', 'userpet', 'check_in_date', 'check_out_date')},
            },
        ),
    ]
