# Generated by Django 3.0.4 on 2020-03-31 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0011_auto_20200331_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_price', models.FloatField(default=0.0)),
                ('payment_status', models.CharField(choices=[('PAID', 'PAID'), ('PENDING', 'PENDING')], max_length=300)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domigo.Plan')),
                ('userbooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domigo.UserBooking')),
            ],
        ),
    ]
