# Generated by Django 3.0.4 on 2020-04-01 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0012_bookingregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpets',
            old_name='Breed',
            new_name='breed',
        ),
    ]
