# Generated by Django 3.0.4 on 2020-04-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0013_auto_20200401_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
    ]
