# Generated by Django 3.0.4 on 2020-04-03 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0014_plan_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingregister',
            name='userbooking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_entries', to='domigo.UserBooking'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='pet_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='domigo.PetCategory'),
        ),
    ]
