# Generated by Django 3.0.4 on 2020-04-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0015_auto_20200403_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='pet_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='domigo.PetCategory'),
        ),
    ]
