# Generated by Django 3.0.4 on 2020-04-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0016_auto_20200403_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpets',
            name='instructions',
            field=models.CharField(default=1, help_text='Write something about your pet or handling instructions.', max_length=300),
            preserve_default=False,
        ),
    ]
