# Generated by Django 3.0.4 on 2020-04-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0017_userpets_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpets',
            name='description',
            field=models.CharField(help_text='Write something about your pet.', max_length=300),
        ),
        migrations.AlterField(
            model_name='userpets',
            name='instructions',
            field=models.CharField(help_text='Write any special instructions to your pet handler.', max_length=300),
        ),
    ]
