# Generated by Django 3.0.4 on 2020-04-11 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domigo', '0018_auto_20200403_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingregister',
            name='payment_status',
        ),
        migrations.CreateModel(
            name='PaymentReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentreceived', to='domigo.UserBooking')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
