# Generated by Django 3.0.4 on 2020-04-11 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0020_auto_20200412_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceived',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paymentreceived', to='domigo.UserBooking'),
        ),
    ]
