# Generated by Django 3.0.4 on 2020-04-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0021_auto_20200412_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpets',
            name='description',
            field=models.CharField(blank=True, help_text='Write something about your pet.', max_length=300),
        ),
    ]
