# Generated by Django 3.0.5 on 2020-04-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0022_auto_20200412_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceived',
            name='amount_received',
            field=models.FloatField(default=0.0),
        ),
    ]
