# Generated by Django 3.0.5 on 2020-04-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0023_paymentreceived_amount_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
