# Generated by Django 3.0.5 on 2020-05-02 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0024_userbooking_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingRegister',
        ),
    ]
