# Generated by Django 3.0.5 on 2020-05-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0025_auto_20200502_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_price', models.FloatField(default=0.0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domigo.Plan')),
                ('userbooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_entries', to='domigo.UserBooking')),
                ('userpet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domigo.UserPets')),
            ],
            options={
                'unique_together': {('date', 'userpet')},
            },
        ),
    ]
