# Generated by Django 3.0.5 on 2020-05-04 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domigo', '0026_bookingregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingregister',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domigo.Plan'),
        ),
        migrations.AlterField(
            model_name='bookingregister',
            name='userbooking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_entries', to='domigo.UserBooking'),
        ),
        migrations.AlterField(
            model_name='paymentreceived',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentreceived', to='domigo.UserBooking'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='paymentmethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domigo.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='userpet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domigo.UserPets'),
        ),
    ]
