# Generated by Django 3.0.5 on 2020-05-08 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0027_auto_20200504_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='userpet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domigo.UserPets'),
        ),
    ]
