# Generated by Django 3.0.5 on 2020-05-08 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domigo', '0028_auto_20200508_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='userpet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='domigo.UserPets'),
        ),
    ]
